### ISSUE TITLE
Add Heiman CO Detector

### ISSUE THREAD

**Issue by AlainBijl** [slasktrat/com.heiman#1]
When I add my HS1CA-Z device to your app I can only select it as an smoke detector. After successfull detection Homey gives:
No compatible Homey App has been found for this device.
It has been added as a Basic Z-Wave device.

What can I do to help?

**Comment by slasktrat** [comment]
Hi. Version 1.0.1 have support for the CO detector. It has been sent to review and should hopefully be available soon.

**Comment by AlainBijl** [comment]
1.0.1 works perfect. Thanks!

**Comment by AlainBijl** [comment]
Thanks! U2! :)
