### ISSUE TITLE
Unable to add the Smoke Sensor

### ISSUE THREAD

**Issue by DomoticaBlog** [slasktrat/com.heiman#10]
Hi,

I'm making a review of the Heiman Smoke Detector. But when i tried to add it i get the following error:
status.request.timeout

I tried resetting the sensor but no luck. Also bring it closer to the Homey did not work.This sensor works fine on other controllers. Could it be that i have a newer firmware of the sensor?

Specs are:
Firmware: 1.10
Makerid: 608
Product type id: 32766
Product id: 4096

Thank you for the help.

**Comment by slasktrat** [comment]
Thanks for reporting. This id is now be supported (from v1.0.5)
