### ISSUE TITLE
Smoke alarm remains "armed"

### ISSUE THREAD

**Issue by petski** [slasktrat/com.heiman#20]
After pressing the test button on one of my smoke devices, the device keeps having a "exclamation mark" because it thinks the smoke alarm is still active. It's not possible to clear this status somehow. Seems like a race condition of some sort, since not all of my smoke sensors show this behaviour.

![Screenshot_20200729-221344](https://user-images.githubusercontent.com/116610/88850138-34b4b800-d1eb-11ea-95e8-07acb711d82e.jpg)

**Comment by petski** [comment]
Other users seem to have this too, i.e. https://community.athom.com/t/fibaro-smoke-sensor-won-t-remove-smoke-alarm-trigger/16611/5

**Comment by slasktrat** [comment]
Hi. Hopefully I've found a fix for this issue, can you please test with the beta version of the app? https://homey.app/no-no/app/com.heiman/Heiman/test/

**Comment by petski** [comment]
Thanks!

After installing v1.0.9, the armed alarm was gone. Not sure the reinstall **or** your fix triggered this (hope the latter). Anything I can do to test this any further?

**Comment by slasktrat** [comment]
Thanks for testing. Do you mean reinstall(/upgraded) of app, or did you exclude and reinclude the smoke alarm? Reinstall of app should not have any effect, so sounds like the fix worked. 👍

**Comment by petski** [comment]
I reinstalled/upgraded the app. Glad it's fixed now.

**Comment by petski** [comment]
Slightly off topic: When will v1.0.9, containing this fix, be released?
