### ISSUE TITLE
Smart combustible gas sensor

### ISSUE THREAD

**Issue by mike02spb** [slasktrat/com.heiman#7]
Hello! Have you any plans to support Heiman gas sensor?
Thank you for you work!

**Comment by Socev** [comment]
I'll second that request!

**Comment by mapulu** [comment]
I send a PR with the adding support of the Heiman Gas Sensor Z-Wave Plus

**Comment by mike02spb** [comment]
But it's still didn't supported

**Comment by slasktrat** [comment]
Thanks for PR, new version sent to Athom for review now :)
