### ISSUE TITLE
rebranded: Heiman Smart Smoke Sensor HS1SA disguised as ABUS Smoke Smoke Sensor

### ISSUE THREAD

**Issue by glupschis-home** [slasktrat/com.heiman#8]
Hello!
I would like to use the smoke detectors ABUS Z-Wave SHRM10000 in Homey. They are identical to Heiman Smart Smoke Sensor HS1SA. Is it possible to modify the Heiman App for Homey for the ABUS Smoke Sensor to work? (add the device id)?

For more informations  please take a look this thread in on homey comunity:

[https://community.athom.com/t/einbindung-von-abus-z-wave-rauchmelder-art-nr-shrm10000/12304](url)

**Comment by glupschis-home** [comment]
I also have these Heiman gas sensors HS1CG-Z.
Maybe these can also be integrated into the Homey app?

[http://www.heimantech.com/product/82.html](url)

**Comment by glupschis-home** [comment]
The Heiman app is nice. Really!
But if nobody cares anymore about updating them, it is meaningless in the medium term. :-/

**Comment by mapulu** [comment]
It is added in v1.0.4
