### ISSUE TITLE
Alert stays active

### ISSUE THREAD

**Issue by buszit** [slasktrat/com.heiman#9]
Hello, 

I just added two Heiman smoke detectors.
I tested one with real smoke, which worked fine.
But now the alarm mode remains on. (exclamation mark in homey dashboard).

Is there a way to reset the alarm?

https://community.athom.com/t/heiman-smoke-detector-remains-in-alarm-mode/12434

Thanks!

**Comment by mapulu** [comment]
The test button should reset it.
